### ISSUE TITLE
Mise à jour pour Quasar ?

### ISSUE THREAD

**Issue by a1ex4** [Sheppounet/script.pulsar.cpb#4]
Pulsar à été abandonné et [une de ses fork](https://github.com/scakemyer/plugin.video.quasar) est trés activement développée, serait-il possible de mettre à jour le provider t411 pour Quasar ? :) 

Merci pour ton excellent boulot! ;)

**Comment by Sheppounet** [comment]
Le T411 ? Mais le mien n'a jamais été fini, un autre développeur l'avait fini avant et je n'ai fait que publier mes sources en l'état.
J'ai prévu de les passer tous les 3 sous Quasar, mais je manque un peu de temps en ce moment (et j'attendais aussi que Quasar se stabilise bien).

**Comment by a1ex4** [comment]
En me basant sur ton code je l'ai adapté et terminé au final, il est sur mon git et aussi sur le repo des providers. Bien sur je t'ai cité et mis comme auteur :)
